[package]
name = "ds210_project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
petgraph = "0.6.4"
ndarray = "0.15.6"
dot = "0.1.4"
plotters = "0.3.4"
rand = "0.8.5"
